name: Dispatch Event on Tag Creation
on:
  create:
    # Trigger the action only when a new tag is created
    tags:
      - '*'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: oat-sa/taocloud-ami-luoss
          event-type: tag-build-ami
          client-payload: '{"tag": "${{ github.ref }}"}'