name: Dispatch Event on Tag Creation
on:
  create:
    # Trigger the action only when a new tag is created
    tags:
      - '*'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch event
        uses: octokit/request-action@v2.x
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: oat-sa/taocloud-ami-luoss
          ref: refs/heads/tag-build-ami
          event-type: tag-build-ami
          client-payload: '{"tag": "${{ github.ref }}", "branch": "tag-build-ami"}'