name: Update taocloud-ami-luoss on new TAO Community release

on:
  create:
    tags: '*'

jobs:
  build:
  dispatch:
    needs: build
    strategy:
      matrix:
        repo: ['oat-sa/taocloud-ami-luoss']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: build-ami
          ref: refs/heads/tag-build-ami
