name: Continuous integration

on:
  push:
    branches: [ master, release* ]
  pull_request:
    branches: [ master, release* ]

jobs:
  ci:
    runs-on: ${{ matrix.operating-system }}
    if: "!contains(github.event.head_commit.message, '[ci]')"

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-version: [ '7.4', '8.0', '8.1' ]
        include:
          - php-version: '7.4'
            coverage: true

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Disable NPM bridge
        run: composer config allow-plugins.oat-sa/composer-npm-bridge false --no-interaction --no-plugins

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run tests
        uses: mathiasvr/command-output@v1
        id: tests
        with:
          run: ./test.sh {{ matrix.coverage && '-c' }}
        continue-on-error: true

      - name: Merge coverage reports
        run: php -dxdebug.mode=coverage -derror_reporting=24575 vendor/bin/phpunit-merger coverage coverage --html=clover clover.xml
        if: ${{ matrix.coverage }}

      - name: Generate a coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        if: ${{ matrix.coverage }}
        with:
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: ${{ matrix.coverage }}
        with:
          report_paths: 'log/*/junit.xml'

      - name: Deploy coverage reports
        id: deploy
        uses: nwtgck/actions-netlify@v1
        if: ${{ matrix.coverage }}
        with:
          publish-dir: ./clover
          alias: deploy-preview-${{ github.event.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-branch: master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - uses: peter-evans/find-comment@v2
        id: fc
        if: ${{ matrix.coverage }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Test results

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ matrix.coverage }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Test results
            ${{ steps.tests.outcome != 'success' && '❌ Some tests have failed. See the build log for details' || '✅' }}
            
            [_Coverage report_](${{ steps.deploy.outputs.deploy-url }})
          edit-mode: replace

      - name: Fail the job if tests weren't OK
        run: exit 1
        if: steps.tests.outcome != 'success'
