name: Continuous integration

on:
  push:
    branches: [ master, release* ]
  pull_request:
    branches: [ master, release* ]

jobs:
  ci:
    runs-on: ${{ matrix.operating-system }}
    if: "!contains(github.event.head_commit.message, 'ci: add updated coverage_badge.xml')"

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-version: [ '7.4', '8.0', '8.1' ]
        include:
          - php-version: '7.4'
            coverage: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Disable NPM bridge
        run: composer config allow-plugins.oat-sa/composer-npm-bridge false --no-interaction --no-plugins

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run tests
        run: ./test.sh ${{ matrix.coverage && '-c' }}
        continue-on-error: true

      - name: Publish a test report
        uses: mikepenz/action-junit-report@v3
        id: junit
        with:
          report_paths: 'log/*/junit.xml'

      - name: Parse the the reports
        id: report
        run: grep testFailed log/*/teamcity.txt -R > /tmp/failures.txt

      - name: Job summary
        uses: mathiasvr/command-output@v1
        id: summary
        with:
          run: |
            cat << EOF
            # Summary ${{ matrix.php-version }}
            |💯 Total|✅ Passed|⏭️ Skipped|❌ Failed|
            |-|-|-|-|
            |${{ steps.junit.outputs.total }}|${{ steps.junit.outputs.passed }}|${{ steps.junit.outputs.skipped }}|${{ steps.junit.outputs.failed }}|
            EOF
            php ./.github/parse-reports.php

      - uses: peter-evans/find-comment@v2
        id: summary-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Summary ${{ matrix.php-version }}

      - name: Create or update summary comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.summary-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.summary.outputs.stdout }}
          edit-mode: replace

      - name: Merge coverage reports
        run: vendor/bin/phpunit-merger coverage coverage --html=clover clover.xml
        if: ${{ matrix.coverage }}

      - name: Generate a coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        if: ${{ matrix.coverage }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push a coverage badge
        uses: EndBug/add-and-commit@v9
        if: ${{ matrix.coverage }}
        with:
          add: coverage_badge.svg
          commit: --signoff
          message: 'ci: add updated coverage_badge.xml'

      - name: Deploy coverage reports
        id: deploy
        uses: nwtgck/actions-netlify@v1
        if: ${{ matrix.coverage }}
        with:
          publish-dir: ./clover
          alias: deploy-preview-${{ github.event.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: false
          enable-commit-comment: false
          production-branch: master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - uses: peter-evans/find-comment@v2
        id: coverage-comment
        if: ${{ matrix.coverage }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Coverage report

      - name: Create or update coverage-report comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ matrix.coverage }}
        with:
          comment-id: ${{ steps.coverage-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: '[🔗 Coverage report](${{ steps.deploy.outputs.deploy-url }})'
          edit-mode: replace

      - name: Job summary
        run: echo "${{ steps.summary.outputs.stdout }}" >> $GITHUB_STEP_SUMMARY

      - name: Fail the job if tests weren't OK
        run: exit ${{ steps.junit.outputs.failed }}
